### ISSUE TITLE
Samples are completely missing from output .it files

### ISSUE THREAD

**Issue by beanieaxolotl** [AnnoyedArt1256/gax2it#2]
I tried both Jackie Chan Adventures - Legend of the Dark Hand (since that was GAX 2) and The Adventures of Jimmy Neutron: Attack of the Twonkies (a legally dumped copy), and both have the symptom of not.. having any samples? I haven't tried any other games, but I believe this happens in all of them.

![image](https://github.com/user-attachments/assets/927d2b11-a6ba-4c78-805f-a0cb7ba46886)

**Comment by AnnoyedArt1256** [comment]
hmm, that issue doesn't seem to happen on the two systems I've tested gax2it on (my iPhone w/ the a-shell app and my main Linux Mint laptop). can you send the command-line output when converting?

**Comment by beanieaxolotl** [comment]
```
> GAX library version | GAX Sound Engine 3.05 (Aug 13 2003)
> Scanning for valid song settings..

>> Song setting data found at 0x81457f4
>> Song setting data found at 0x8146018
>> Song setting data found at 0x814658c
>> Song setting data found at 0x8147354
>> Song setting data found at 0x81476fc
>> Song setting data found at 0x81479c8
>> Song setting data found at 0x8147dfc
>> Song setting data found at 0x8148488
>> Song setting data found at 0x814890c
>> Song setting data found at 0x8148df0
>> Song setting data found at 0x8149430
>> Song setting data found at 0x8149c94
>> Song setting data found at 0x8149fb0
>> Song setting data found at 0x814a8c4
>> Song setting data found at 0x814b080
>> Song setting data found at 0x814bd28
>> Song setting data found at 0x814c854
>> Song setting data found at 0x814d6cc

 Songs found | 18

> Composed by Martin Schioeler
> Song 00: FE01_1

0x1457f4
21025

> Composed by Martin Schioeler
> Song 01: FE07_1

0x146018
21025

> Composed by Martin Schioeler
> Song 02: FE03_1

0x14658c
21025

> Composed by Martin Schioeler
> Song 03: IGM04_2

0x147354
21025

> Composed by Martin Schioeler
> Song 04: FE06_1

0x1476fc
21025

> Composed by Martin Schioeler
> Song 05: IGM01_1

0x1479c8
15769

> Composed by Martin Schioeler
> Song 06: IGM02_1

0x147dfc
15769

> Composed by Martin Schioeler
> Song 07: FE04_1

0x148488
21025

> Composed by Martin Schioeler
> Song 08: FE05_1

0x14890c
21025

> Composed by Martin Schioeler
> Song 09: IGM03_1

0x148df0
15769

> Composed by Martin Schioeler
> Song 10: IGM10_1

0x149430
21025

> Composed by Martin Schioeler
> Song 11: IGM12_1

0x149c94
21025

> Composed by Martin Schioeler
> Song 12: IGM05_1

0x149fb0
21025

> Composed by Martin Schioeler
> Song 13: IGM13_1

0x14a8c4
21025

> Composed by Martin Schioeler
> Song 14: IGM08_1

0x14b080
21025

> Composed by Martin Schioeler
> Song 15: IGM09_2

0x14bd28
21025

> Composed by Martin Schioeler
> Song 16: FE02_1

0x14c854
21025

> Composed by Martin Schioeler
> Song 17: IGM11_1

0x14d6cc
21025
```

The output seems normal to me. I use a Windows 10 (I'm thinking of switching to Linux/Ubuntu but hear me out) computer with Python in Command Prompt by the way.

**Comment by AnnoyedArt1256** [comment]
yea, the command line output is the same on my machines as well. maybe use another (newer) OpenMPT version for loading the modules?

**Comment by beanieaxolotl** [comment]
I'm using the latest stable version of OpenMPT: that being OpenMPT 1.13.13.00.
Update: I checked, and not even the latest development versions have the samples loaded

![image](https://github.com/user-attachments/assets/62e95071-57eb-4475-9aea-a600864f5d27)

**Comment by AnnoyedArt1256** [comment]
so, i found out that the samples worked because I was using an **older** version of OpenMPT, which was more lenient in terms of sample loading. I just fixed the issue in the newest commit/version btw

**Comment by beanieaxolotl** [comment]
thx! it works now
